import { runCompletionWithTools, type Message, type ToolCall, type ToolDefinition } from "./client.js";
import { LocallyError } from "./errors.js";
import { grepFiles, globFiles, GREP_SCHEMA, GLOB_SCHEMA } from "../tools/explore-files.js";
import { readFile, READ_FILE_SCHEMA } from "../tools/read-file.js";
import { writeFile, WRITE_FILE_SCHEMA } from "../tools/write-file.js";
import { patchFile, PATCH_FILE_SCHEMA } from "../tools/patch-file.js";
import { runShell, RUN_SHELL_SCHEMA } from "../tools/run-shell.js";
import type { ResolvedAgentConfig } from "../config.js";

/**
 * How a tool touches the filesystem — declared, not inferred from its name.
 *
 * runAgenticTask used to wrap tools in a `switch` over their names to apply the allowedRoots fence
 * and record what the run had seen, with a `default:` that returned the tool unwrapped. Renaming a
 * tool would therefore have silently dropped it out of the sandbox *and* out of the coverage note,
 * with no error anywhere. Declaring the contract on the tool makes that a type error instead.
 */
export interface ToolFence {
  /** The argument key holding the path this tool touches. Validated against allowedRoots. */
  pathKey: string;
  /** Whether the path must already exist (reads and searches) or may be created (writes). */
  mustExist: boolean;
  /** Fill in the task's own directory when the model omits the path, rather than erroring. */
  defaultsToTaskRoot?: boolean;
  /** What a successful call proves about the files it touched, for explore_task's coverage note. */
  evidence?: "read" | "searchHits" | "listing";
  /** Whether the config's `ignorePatterns` are merged into this tool's `ignore_patterns` argument. */
  mergesIgnorePatterns?: boolean;
}

export interface AgentTool {
  definition: ToolDefinition;
  handler: (args: unknown) => Promise<string>;
  fence: ToolFence;
}

export interface AgentRunResult {
  text: string;
  model: string;
  /** Tokens the local model processed (prompt/input) across all loop iterations. */
  promptTokens: number;
  /** Tokens generated by the local model across all loop iterations. */
  completionTokens: number;
  /** Number of completion calls made (loop iterations, plus a forced final call if capped). */
  iterations: number;
  /** Wall-clock time spent in the loop. */
  durationMs: number;
  /**
   * True when the loop ran out of iterations and the answer came from the forced final call
   * rather than the model deciding it was done. A run that stopped because it hit the budget
   * has a different reliability profile from one that stopped because it finished, and the
   * iteration count alone does not distinguish them (issue #13).
   */
  cappedAtMaxIterations: boolean;
  /**
   * Distinct files opened with read_file. Filled in by the caller that owns the tool handlers
   * (see runAgenticTask); the loop itself dispatches tools by name and does not inspect them.
   */
  filesRead: number;
  /**
   * Canonical paths of those files. The count alone cannot answer the question issue #16 asks —
   * which of the files this answer describes did the run never actually look at — so the
   * identities are carried, not just the tally.
   */
  filesReadPaths: string[];
  /** Canonical paths the model saw matching lines from, via an explore_files search. */
  filesMatchedPaths: string[];
  /** Canonical paths a directory listing named — the file's existence was seen, not its contents. */
  filesListedPaths: string[];
  /**
   * True when the run was asked to keep sweeping before its answer was accepted. Set by
   * runAgenticTask, which owns the sweep floor; the loop only knows it was handed a callback.
   */
  nudged: boolean;
}

/**
 * Three sharp tools rather than one with a mode switch: Read opens a file, Grep searches contents,
 * Glob finds files by name. The names are the ones every other coding agent uses, which is what
 * every model has seen most of in training — a model guessing at this surface should guess right.
 */
export const AGENT_TOOLS: AgentTool[] = [
  {
    definition: {
      type: "function",
      function: {
        name: "Grep",
        description:
          "Search file contents with ripgrep (or grep) and get back matching lines as path:line:text. This is your primary tool — prefer several narrow searches over one broad sweep.",
        parameters: GREP_SCHEMA,
      },
    },
    handler: (args) => grepFiles(args as Parameters<typeof grepFiles>[0]),
    fence: { pathKey: "path", mustExist: true, defaultsToTaskRoot: true, evidence: "searchHits", mergesIgnorePatterns: true },
  },
  {
    definition: {
      type: "function",
      function: {
        name: "Glob",
        description:
          "Find files by name pattern (e.g. \"*.ts\", \"src/**/*.tsx\") and get back their paths, line counts and sizes. Use this to see what exists before deciding what to open — never to guess a filename from a convention.",
        parameters: GLOB_SCHEMA,
      },
    },
    handler: (args) => globFiles(args as Parameters<typeof globFiles>[0]),
    fence: { pathKey: "path", mustExist: true, defaultsToTaskRoot: true, evidence: "listing", mergesIgnorePatterns: true },
  },
  {
    definition: {
      type: "function",
      function: {
        name: "Read",
        description:
          "Read a file by absolute path. Output is line-numbered, so cite the numbers you see rather than counting. Pass offset and limit to read just the range you need.",
        parameters: READ_FILE_SCHEMA,
      },
    },
    handler: (args) => readFile(args as Parameters<typeof readFile>[0]),
    fence: { pathKey: "path", mustExist: true, evidence: "read" },
  },
];

export const RUN_AGENT_TOOLS: AgentTool[] = [
  ...AGENT_TOOLS,
  {
    definition: {
      type: "function",
      function: {
        name: "write_file",
        description:
          "Write content to a file at the given absolute path, creating parent directories as needed. Use this to create or overwrite files.",
        parameters: WRITE_FILE_SCHEMA,
      },
    },
    handler: (args) => writeFile(args as Parameters<typeof writeFile>[0]),
    fence: { pathKey: "path", mustExist: false },
  },
  {
    definition: {
      type: "function",
      function: {
        name: "patch_file",
        description:
          "Replace an exact string in a file. Prefer this over write_file for targeted edits — safer than rewriting the whole file.",
        parameters: PATCH_FILE_SCHEMA,
      },
    },
    handler: (args) => patchFile(args as Parameters<typeof patchFile>[0]),
    fence: { pathKey: "path", mustExist: false },
  },
  {
    definition: {
      type: "function",
      function: {
        name: "run_shell",
        description:
          "Run a nondestructive shell command from the allowlist. Use to check compilation errors, run tests, inspect git state, or verify output.",
        parameters: RUN_SHELL_SCHEMA,
      },
    },
    handler: (args) => runShell(args as Parameters<typeof runShell>[0]),
    fence: { pathKey: "cwd", mustExist: true, defaultsToTaskRoot: true },
  },
];

const MAX_ITERATIONS_DEFAULT = 10;

/**
 * Consulted when the model offers a final answer. Return text to push back as a user turn and keep
 * the loop running, or null to accept the answer.
 *
 * This is the only thing that lets a caller's "how widely to search" setting shape the run rather
 * than just flavour the prompt: a "very thorough" sweep that concluded after five iterations of a
 * twenty-iteration budget, having read fewer files than a "medium" one, is what issue #16 measured.
 * The `while` guard still bounds everything, so a policy that always wants more cannot run away.
 */
export type DraftAnswerHook = (draft: { text: string; iterations: number }) => string | null;

export async function runAgentLoop(
  config: ResolvedAgentConfig,
  messages: Message[],
  tools: AgentTool[],
  maxIterations: number = MAX_ITERATIONS_DEFAULT,
  onProgress?: (message: string) => void,
  signal?: AbortSignal,
  onDraftAnswer?: DraftAnswerHook
): Promise<AgentRunResult> {
  const startedAt = Date.now();
  const toolDefs: ToolDefinition[] = tools.map((t) => t.definition);
  const toolMap = new Map<string, AgentTool["handler"]>(
    tools.map((t) => [t.definition.function.name, t.handler])
  );

  let promptTokens = 0;
  let completionTokens = 0;

  // Cache keyed by "toolName:normalizedArgsJson" — return cached results on duplicate calls.
  // Normalized to avoid cache misses from semantically identical but whitespace-differing JSON.
  // Capped at MAX_CACHE_SIZE entries; evicts oldest when full.
  const MAX_CACHE_SIZE = 50;
  const toolResultCache = new Map<string, string>();

  /**
   * Run one tool call and return the text that goes back to the model.
   *
   * In-flight calls are tracked alongside finished ones so that two identical calls in the same
   * parallel batch collapse to a single execution rather than racing to fill the cache.
   */
  const inFlight = new Map<string, Promise<string>>();

  const dispatch = async (toolCall: ToolCall): Promise<string> => {
    const { name, arguments: argsJson } = toolCall.function;
    try {
      // Parsed once — used for cache key normalization and handler invocation.
      let parsedArgs: unknown;
      try {
        parsedArgs = JSON.parse(argsJson);
      } catch {
        throw new Error(`Invalid JSON in tool arguments: ${argsJson}`);
      }
      const cacheKey = `${name}:${JSON.stringify(parsedArgs)}`;

      const cached = toolResultCache.get(cacheKey);
      if (cached !== undefined) {
        // Still reported: from the caller's side a cache hit is activity, and a run that is
        // looping on one repeated call is exactly what a heartbeat should reveal.
        onProgress?.(`[tool: ${name}] ${argsJson} (cached)`);
        return `(already retrieved — returning cached result)\n${cached}`;
      }

      const pending = inFlight.get(cacheKey);
      if (pending) {
        onProgress?.(`[tool: ${name}] ${argsJson} (cached)`);
        return `(already retrieved — returning cached result)\n${await pending}`;
      }

      onProgress?.(`[tool: ${name}] ${argsJson}`);
      const handler = toolMap.get(name);
      if (!handler) return `Error: unknown tool "${name}"`;

      const run = handler(parsedArgs);
      inFlight.set(cacheKey, run);
      let result: string;
      try {
        result = await run;
      } finally {
        inFlight.delete(cacheKey);
      }

      if (toolResultCache.size >= MAX_CACHE_SIZE) {
        toolResultCache.delete(toolResultCache.keys().next().value!);
      }
      toolResultCache.set(cacheKey, result);
      return result;
    } catch (err) {
      return `Error: ${err instanceof Error ? err.message : String(err)}`;
    }
  };

  let iterations = 0;

  // On a completion failure, annotate the error with how far we got so the caller knows
  // whether any local work happened before the failure. Preserves the LocallyError category.
  const augmentProgress = (err: unknown): unknown => {
    if (err instanceof LocallyError && (iterations > 1 || completionTokens > 0)) {
      return new LocallyError(
        `${err.message} (failed after ${iterations} iteration(s), ${completionTokens} tokens generated locally so far)`,
        { category: err.category, origin: err.origin, retriable: err.retriable, fix: err.fix }
      );
    }
    return err;
  };

  // An in-flight completion is aborted by the merged signal inside the client, but tool calls
  // and cache hits run between completions — so the loop also checks at the top of each
  // iteration rather than only noticing on the next fetch.
  const throwIfCancelled = (): void => {
    if (!signal?.aborted) return;
    throw new LocallyError("Task cancelled by the caller.", {
      category: "cancelled",
      origin: "local",
      retriable: true,
      fix: "nothing to fix — re-run the task if the cancellation was not intended.",
    });
  };

  while (iterations < maxIterations) {
    throwIfCancelled();
    iterations++;
    onProgress?.(`[iteration ${iterations}/${maxIterations}]`);

    let turn;
    try {
      turn = await runCompletionWithTools(config, messages, toolDefs, signal);
    } catch (err) {
      throw augmentProgress(err);
    }
    promptTokens += turn.usage?.promptTokens ?? 0;
    completionTokens += turn.usage?.completionTokens ?? 0;

    // Push the full assistant turn (including tool_calls) before processing results.
    // The API requires the assistant message with tool_calls to precede role:"tool" messages.
    messages.push({
      role: "assistant",
      content: turn.content,
      ...(turn.tool_calls ? { tool_calls: turn.tool_calls } : {}),
    });

    if (!turn.tool_calls || turn.tool_calls.length === 0) {
      if (typeof turn.content !== "string") {
        throw new Error("Model returned neither tool calls nor text content.");
      }

      // Only worth asking with iterations left to spend: pushed at the cap, the answer would come
      // from the forced tool-less final call, where the model cannot act on what it was asked.
      const nudge = iterations < maxIterations ? onDraftAnswer?.({ text: turn.content, iterations }) : null;
      if (nudge) {
        onProgress?.("[keep sweeping]");
        messages.push({ role: "user", content: nudge });
        continue;
      }

      return {
        text: turn.content,
        model: config.model,
        promptTokens,
        completionTokens,
        iterations,
        durationMs: Date.now() - startedAt,
        cappedAtMaxIterations: false,
        filesRead: 0,
        filesReadPaths: [],
        filesMatchedPaths: [],
        filesListedPaths: [],
        nudged: false,
      };
    }

    // A turn's tool calls are independent by construction — the model asked for all of them
    // before seeing any result — so they run concurrently. Serially awaiting three or four
    // searches multiplied the wall clock of every iteration for nothing. Results are still
    // pushed in call order: the API requires each role:"tool" message to follow its call.
    const results = await Promise.all(turn.tool_calls.map((toolCall) => dispatch(toolCall)));

    for (let i = 0; i < turn.tool_calls.length; i++) {
      messages.push({
        role: "tool",
        tool_call_id: turn.tool_calls[i].id,
        content: results[i],
      });
    }
  }

  // Max iterations reached — call without tools to force a final text answer
  throwIfCancelled();
  let finalTurn;
  try {
    finalTurn = await runCompletionWithTools(config, messages, undefined, signal);
  } catch (err) {
    throw augmentProgress(err);
  }
  promptTokens += finalTurn.usage?.promptTokens ?? 0;
  completionTokens += finalTurn.usage?.completionTokens ?? 0;
  if (typeof finalTurn.content !== "string") {
    throw new LocallyError(
      `Agent exceeded ${maxIterations} iterations and the model returned no final content.`,
      {
        category: "constraint",
        origin: "local",
        retriable: true,
        fix: "raise \"max_iterations\" on the call, or narrow the task so the model finishes sooner.",
      }
    );
  }
  return {
    text: finalTurn.content,
    model: config.model,
    promptTokens,
    completionTokens,
    iterations: iterations + 1,
    durationMs: Date.now() - startedAt,
    cappedAtMaxIterations: true,
    filesRead: 0,
    filesReadPaths: [],
    filesMatchedPaths: [],
    filesListedPaths: [],
    nudged: false,
  };
}
